import {z} from 'zod';
export const visibilityEngine=z.enum(['chatgpt','gemini','perplexity','copilot','claude','api_model']);
export type VisibilityEngine=z.infer<typeof visibilityEngine>;
const domain=z.string().trim().toLowerCase().transform(s=>s.replace(/^www\./u,'')).pipe(z.string().max(253).regex(/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/u));
const safeText=z.string().trim().refine(s=>!/[\w.+-]+@[\w.-]+\.[a-z]{2,}/iu.test(s),'Verwijder persoonlijke e-mailadressen.');
export const visibilityEntityInput=z.object({name:z.string().trim().min(3).max(120).regex(/[\p{L}\p{N}]/u,'Gebruik een herkenbare naam.'),kind:z.enum(['own','competitor']),aliases:z.array(z.string().trim().min(3).max(120).regex(/[\p{L}\p{N}]/u,'Gebruik een herkenbare naam.')).max(15),domains:z.array(domain).max(10)});
export interface VisibilityEntity extends z.infer<typeof visibilityEntityInput>{id:string;}
export const visibilityPromptInput=z.object({courseVersionId:z.uuid(),text:safeText.pipe(z.string().min(10).max(1200)),family:z.string().trim().min(2).max(80),topic:z.string().trim().min(2).max(160),intent:z.enum(['discovery','comparison','reputation','problem']),persona:z.string().max(300).default(''),source:z.string().max(1000).default('Handmatig voorstel; zoekvraagvolume onbekend')});
export interface VisibilityPrompt extends z.infer<typeof visibilityPromptInput>{id:string;version:number;state:'proposed'|'approved';kind:'unbranded'|'branded'|'competitor_named';}
export const visibilityBenchmarkInput=z.object({courseVersionId:z.uuid(),name:z.string().trim().min(3).max(160),promptIds:z.array(z.uuid()).min(1).max(30),engines:z.array(visibilityEngine).min(1).max(6),repeats:z.number().int().min(1).max(5).default(1),country:z.string().regex(/^[A-Z]{2}$/u).default('NL'),language:z.string().regex(/^[a-z]{2}$/u).default('nl'),sessionType:z.enum(['fresh','personalized','unknown']).default('fresh'),searchMode:z.enum(['on','off','unknown']).default('unknown')}).refine(x=>new Set(x.promptIds).size===x.promptIds.length&&new Set(x.engines).size===x.engines.length,'Dubbele prompts of engines zijn niet toegestaan.');
const evidenceUrl=z.url({protocol:/^https$/u}).max(2048).refine(s=>!/^https:\/\/[^/]*@/iu.test(s),'Gebruik een HTTPS-link zonder inloggegevens.');
export const visibilityObservationInput=z.object({promptId:z.uuid(),engine:visibilityEngine,repetition:z.number().int().min(1).max(5),status:z.enum(['success','blocked','unavailable','extraction_error']),rawResponse:safeText.pipe(z.string().max(50000)).default(''),capturedAt:z.iso.datetime({offset:true}),model:z.string().trim().max(120).nullable().default(null),citations:z.array(evidenceUrl).max(50).default([]),citationCapture:z.enum(['complete','unknown']).default('unknown'),failureReason:z.string().trim().max(1000).default(''),evidenceUrl:evidenceUrl.nullable().default(null),sanitized:z.literal(true)}).refine(x=>x.status==='success'?x.rawResponse.length>=20:x.failureReason.length>=5,'Succes vereist een volledig antwoord; een mislukking vereist een reden.').refine(x=>x.status==='success'||(!x.rawResponse&&!x.citations.length),'Bewaar geen antwoord bij een mislukte extractie.');
export type VisibilityObservationInput=z.infer<typeof visibilityObservationInput>;
export interface VisibilityObservation extends VisibilityObservationInput {id:string;captureMethod:'manual_import';responseHash:string;mentions:{entityId:string;name:string;kind:'own'|'competitor';evidence:string}[];citedDomains:string[];}
export interface VisibilityMetrics {kind:string;engine:string;planned:number;completed:number;successful:number;failed:number;uniquePrompts:number;mentionCount:number;mentionRate:number|null;citationEligible:number;ownCitationCount:number;citationRate:number|null;entities:{id:string;name:string;mentions:number;shareOfVoice:number|null}[];recommendationRate:null;accuracyRate:null;averageMentionPosition:null;}
export interface VisibilityRun {id:string;benchmarkId:string;name:string;courseVersionId:string;createdAt:string;status:'pending'|'partial'|'completed'|'failed';country:string;language:string;sessionType:string;searchMode:string;repeats:number;engines:VisibilityEngine[];prompts:VisibilityPrompt[];entities:VisibilityEntity[];observations:VisibilityObservation[];metrics:VisibilityMetrics[];}
