import { z } from 'zod';

/** Every persisted entity is keyed by a UUID generated by the database. */
export const uuid = z.uuid();
export type Uuid = z.infer<typeof uuid>;

/**
 * Human-readable, URL-safe identifier used for labels and courses.
 * Deliberately narrow so it can be embedded in paths without escaping.
 */
export const slug = z
  .string()
  .min(2)
  .max(64)
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/u, 'Alleen kleine letters, cijfers en koppeltekens.');
export type Slug = z.infer<typeof slug>;

/**
 * A URL that may safely become a link or an `href`.
 *
 * **`z.url()` is not this.** It validates URL *syntax*, and
 * `javascript:alert(1)`, `data:text/html,…` and `vbscript:…` are all
 * syntactically valid URLs — `z.url()` accepts every one of them. Anywhere such
 * a value reaches an anchor's `href`, clicking it executes script in our own
 * origin; anywhere it reaches generated HTML, it ships in a file we produced.
 *
 * That matters here because these URLs are not ours. A CTA link comes from a
 * brief, a source URL comes from a model reading a fetched page — both are
 * untrusted input travelling towards markup. The scheme is therefore checked at
 * the contract boundary, so every consumer is protected by construction rather
 * than by each one remembering.
 *
 * Only `http:` and `https:`. Not `mailto:` — no field needs it today, and a
 * narrow rule is easier to widen deliberately than to tighten later.
 */
export const webUrl = z
  .url()
  /*
   * Matched rather than parsed, on purpose.
   *
   * This package is deliberately environment-free — `lib: ["ES2023"]`,
   * `types: []` — so it has no `URL` constructor, and that is a property worth
   * keeping: a contract that cannot reach for a host API cannot behave
   * differently on the server than in the browser. Two host parsers
   * normalising an edge case differently is precisely how a scheme check gets
   * bypassed.
   *
   * `z.url()` has already established that the value is a syntactically valid
   * URL; this only decides the scheme. Requiring `//` after it is what
   * excludes `javascript:` and `data:`, which have no authority component.
   */
  .refine((value) => /^https?:\/\//iu.test(value), {
    message: 'Alleen http- en https-adressen zijn toegestaan.',
  });
export type WebUrl = z.infer<typeof webUrl>;

/** ISO-8601 timestamp, always serialised in UTC. */
export const isoTimestamp = z.iso.datetime({ offset: true });
export type IsoTimestamp = z.infer<typeof isoTimestamp>;

/**
 * Monotonically increasing version number on an immutable entity version row.
 * Versions are never mutated in place; a revision creates version n+1.
 */
export const versionNumber = z.number().int().min(1);

/** Money is stored and transported as integer eurocents — never as a float. */
export const cents = z.number().int().min(0);

/** Content language, defaulting to Dutch and overridable per campaign. */
export const contentLanguage = z.enum(['nl', 'en', 'de', 'fr']);
export type ContentLanguage = z.infer<typeof contentLanguage>;

/**
 * Optimistic-concurrency token. Clients echo the value they last read; the
 * server refuses the write when it no longer matches, so two people editing
 * the same record cannot silently overwrite each other.
 */
export const concurrencyToken = z.string().min(1).max(128);

/**
 * Every record that leaves the API carries the origin of its data so the UI can
 * show provenance and so demo content is never mistaken for real content.
 */
export const dataOrigin = z.enum([
  /** Seeded development data. Always surfaced in the UI as "Demo".        */
  'demo',
  /** Entered or uploaded by a user.                                       */
  'user',
  /** Extracted from a user-supplied document, pending user confirmation.  */
  'extracted',
  /** Retrieved from an external source with a recorded URL and date.      */
  'external',
  /** Produced by an AI model. Never treated as verified fact.             */
  'ai_generated',
]);
export type DataOrigin = z.infer<typeof dataOrigin>;

/**
 * Confidence in a field that was extracted rather than entered. Extraction is
 * a proposal: nothing marked `unverified` may reach a publish-ready export.
 */
export const verificationState = z.enum(['unverified', 'user_confirmed', 'conflicting']);
export type VerificationState = z.infer<typeof verificationState>;
