import {sql} from 'drizzle-orm';
import {createHash,randomUUID} from 'node:crypto';
import {visibilityEntityInput,visibilityPromptInput,visibilityBenchmarkInput,createCampaignInput,type VisibilityEntity,type VisibilityPrompt,type VisibilityObservation,type VisibilityRun,type CurrentUser} from '@c360/contracts';
import {z} from 'zod';
import type {Db} from '../../core/db/types.js';
import {requireLabelPermission} from '../../core/authz/policy.js';
import {AppError} from '../../core/errors/app-error.js';
import type {CampaignService} from '../campaigns-briefs/service.js';
import type {CourseService} from '../courses/service.js';
import {normalize,matchedEntities,promptKind,canonicalCitation,metrics,similarPrompts,ownDomain} from './analysis.js';
import {ManualImportAdapter} from './adapters.js';
type Row=Record<string,unknown>;
const str=(x:unknown):string=>String(x);
function entity(r:Row):VisibilityEntity{return {id:str(r.id),...visibilityEntityInput.parse({name:r.name,kind:r.kind,aliases:r.aliases,domains:r.domains})};}
function prompt(r:Row):VisibilityPrompt{return {id:str(r.id),version:Number(r.version),state:z.enum(['proposed','approved']).parse(r.state),kind:z.enum(['unbranded','branded','competitor_named']).parse(r.kind),...visibilityPromptInput.parse({courseVersionId:r.course_version_id,text:r.text,family:r.family,topic:r.topic,intent:r.intent,persona:r.persona,source:r.source})};}
export class VisibilityService {
 constructor(private readonly campaigns:CampaignService,private readonly courses:CourseService){}
 async entities(db:Db,labelId:string){return (await db.execute(sql`SELECT * FROM visibility_entities WHERE label_id=${labelId} ORDER BY kind DESC,name`)).rows.map(entity);}
 async overview(db:Db,user:CurrentUser,labelId:string){
 requireLabelPermission(user,labelId,'research:read');
 const [entities,prompts,benchmarks,runs]=await Promise.all([this.entities(db,labelId),db.execute(sql`SELECT * FROM visibility_prompts WHERE label_id=${labelId} ORDER BY created_at DESC`),db.execute(sql`SELECT b.*,ARRAY(SELECT engine FROM visibility_benchmark_engines e WHERE e.benchmark_id=b.id) engines,ARRAY(SELECT prompt_id FROM visibility_benchmark_prompts p WHERE p.benchmark_id=b.id) prompt_ids FROM visibility_benchmarks b WHERE label_id=${labelId} ORDER BY created_at DESC`),db.execute(sql`SELECT r.id,r.benchmark_id,r.created_at,b.name FROM visibility_runs r JOIN visibility_benchmarks b ON b.id=r.benchmark_id WHERE b.label_id=${labelId} ORDER BY r.created_at DESC LIMIT 50`)]);
 return {entities,prompts:prompts.rows.map(prompt).map(p=>({...p,kind:promptKind(p.text,entities)})),benchmarks:benchmarks.rows,runs:runs.rows};
 }
 async addEntity(db:Db,user:CurrentUser,labelId:string,body:unknown,id?:string){
 requireLabelPermission(user,labelId,'campaign:write');const input=visibilityEntityInput.parse(body);
 return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM labels WHERE id=${labelId} FOR UPDATE`);
 const existing=(await tx.execute(sql`SELECT * FROM visibility_entities WHERE label_id=${labelId}`)).rows.map(entity);
 if(id&&!existing.some(e=>e.id===id))throw AppError.notFoundOrForbidden('visibility_entity',id);
 const terms=[input.name,...input.aliases,...input.domains].map(normalize);
 if(new Set(terms).size!==terms.length||existing.filter(e=>e.id!==id).some(e=>[e.name,...e.aliases,...e.domains].some(t=>terms.includes(normalize(t)))||(e.kind==='own'&&input.kind==='own')))throw new AppError('conflict',{publicMessage:'Deze naam/alias bestaat al of er is al een eigen merk. Gebruik ondubbelzinnige namen.'});
 await tx.execute(sql`INSERT INTO visibility_entities(id,label_id,name,kind,aliases,domains) VALUES(${id??randomUUID()},${labelId},${input.name},${input.kind},${sql`ARRAY[${sql.join(input.aliases.map(a=>sql`${a}`),sql`, `)}]::text[]`},${sql`ARRAY[${sql.join(input.domains.map(a=>sql`${a}`),sql`, `)}]::text[]`}) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,kind=EXCLUDED.kind,aliases=EXCLUDED.aliases,domains=EXCLUDED.domains`);
 return {saved:true};});
 }
 async addPrompt(db:Db,user:CurrentUser,labelId:string,body:unknown){
 requireLabelPermission(user,labelId,'research:run');const input=visibilityPromptInput.parse(body);await this.courses.requireVersion(db,labelId,input.courseVersionId);
 const entities=await this.entities(db,labelId);if(!entities.some(e=>e.kind==='own'))throw new AppError('gate_not_passed',{publicMessage:'Configureer eerst het eigen merk.'});
 const existing=(await db.execute(sql`SELECT * FROM visibility_prompts WHERE label_id=${labelId} AND course_version_id=${input.courseVersionId}`)).rows.map(prompt);
 const id=randomUUID();const rows=await db.execute(sql`INSERT INTO visibility_prompts(id,label_id,course_version_id,text,normalized_text,family,topic,intent,persona,source,kind,created_by) VALUES(${id},${labelId},${input.courseVersionId},${input.text},${normalize(input.text)},${input.family},${input.topic},${input.intent},${input.persona},${input.source},${promptKind(input.text,entities)},${user.userId}) ON CONFLICT DO NOTHING RETURNING id`);
 return {id:rows.rows[0]?.id??existing.find(p=>normalize(p.text)===normalize(input.text))?.id,created:rows.rows.length>0,similar:similarPrompts(input.text,existing).map(p=>({id:p.id,text:p.text})),similarityMethod:'Token-overlap ≥ 0.8; geen semantische classificatie'};
 }
 async propose(db:Db,user:CurrentUser,labelId:string,courseId:string){
 requireLabelPermission(user,labelId,'research:run');const course=await this.courses.requireVersion(db,labelId,courseId);
 const own=(await this.entities(db,labelId)).find(e=>e.kind==='own');if(!own)throw new AppError('gate_not_passed');
 const patterns=[['discovery','Welke opleiders bieden {c} aan?'],['comparison','Hoe vergelijk ik aanbieders van {c}?'],['problem','Hoe combineer ik {c} met een fulltime baan?'],['problem','Waar moet ik op letten voordat ik aan {c} begin?'],['discovery','Welke soorten lesvormen bestaan er voor {c}?'],['comparison','Wat zijn de verschillen tussen klassikaal en online leren voor {c}?'],['problem','Welke ondersteuning kan ik verwachten bij {c}?'],['problem','Hoe bepaal ik of {c} past bij mijn leerdoel?'],['discovery','Welke informatie heb ik nodig om een aanbieder voor {c} te kiezen?'],['comparison','Hoe vergelijk ik de totale kosten van {c}?'],['problem','Welke vragen stel ik tijdens een adviesgesprek over {c}?'],['discovery','Welke vaardigheden staan centraal bij {c}?'],['problem','Hoe beoordeel ik de kwaliteit van {c}?'],['comparison','Hoe vergelijk ik de begeleiding van opleiders voor {c}?'],['problem','Wat zijn veelvoorkomende twijfels bij het kiezen van {c}?'],['discovery','Waar vind ik betrouwbare informatie over {c}?'],['problem','Hoe kies ik {c} als mijn werkgever de opleiding betaalt?'],['comparison','Waarop let een werkgever bij het kiezen van {c}?'],['problem','Hoe bereid ik mij voor op {c}?'],['discovery','Welke alternatieven zijn er voor {c}?'],['reputation',`Welke informatie is bekend over ${own.name} en {c}?`],['reputation',`Welke vragen moet ik ${own.name} stellen over {c}?`],['reputation',`Wat zeggen bronnen over ${own.name} als opleider?`],['reputation',`Welke opleidingsvormen beschrijft ${own.name} voor {c}?`]];
 let created=0;for(const [intent,text]of patterns){const result=await this.addPrompt(db,user,labelId,{courseVersionId:courseId,text:text!.replaceAll('{c}',course.name),family:intent,topic:course.name,intent,source:'Deterministisch voorstel uit cursusnaam; geen gemeten vraagvolume',persona:''});if(result.created)created++;}return {created};
 }
 async approve(db:Db,user:CurrentUser,labelId:string,id:string){requireLabelPermission(user,labelId,'course:approve');const rows=await db.execute(sql`UPDATE visibility_prompts SET state='approved',approved_by=COALESCE(approved_by,${user.userId}) WHERE id=${id} AND label_id=${labelId} RETURNING id`);if(!rows.rows.length)throw AppError.notFoundOrForbidden('prompt',id);return {approved:true};}
 async benchmark(db:Db,user:CurrentUser,labelId:string,body:unknown){
 requireLabelPermission(user,labelId,'research:run');const input=visibilityBenchmarkInput.parse(body);await this.courses.requireVersion(db,labelId,input.courseVersionId);
 const entities=await this.entities(db,labelId);if(!entities.some(e=>e.kind==='own'))throw new AppError('gate_not_passed');
 return db.transaction(async tx=>{const prompts=await tx.execute(sql`SELECT id FROM visibility_prompts WHERE label_id=${labelId} AND course_version_id=${input.courseVersionId} AND state='approved' AND id IN (${sql.join(input.promptIds.map(id=>sql`${id}`),sql`,`)})`);if(prompts.rows.length!==input.promptIds.length)throw new AppError('gate_not_passed',{publicMessage:'Selecteer uitsluitend goedgekeurde vragen van deze opleiding.'});
 const id=randomUUID();await tx.execute(sql`INSERT INTO visibility_benchmarks(id,label_id,course_version_id,name,country,language,session_type,search_mode,repeats,entity_snapshot) VALUES(${id},${labelId},${input.courseVersionId},${input.name},${input.country},${input.language},${input.sessionType},${input.searchMode},${input.repeats},${JSON.stringify(entities)}::jsonb)`);
 for(const promptId of input.promptIds)await tx.execute(sql`INSERT INTO visibility_benchmark_prompts VALUES(${id},${promptId})`);
 for(const engine of input.engines)await tx.execute(sql`INSERT INTO visibility_benchmark_engines VALUES(${id},${engine})`);return {id};});
 }
 async start(db:Db,user:CurrentUser,labelId:string,id:string,key:string){requireLabelPermission(user,labelId,'research:run');const b=await db.execute(sql`SELECT id FROM visibility_benchmarks WHERE id=${id} AND label_id=${labelId}`);if(!b.rows.length)throw AppError.notFoundOrForbidden('benchmark',id);
 const result=await db.execute(sql`INSERT INTO visibility_runs(benchmark_id,created_by,request_key) VALUES(${id},${user.userId},${key}) ON CONFLICT(benchmark_id,request_key) DO UPDATE SET request_key=EXCLUDED.request_key RETURNING id`);return {id:result.rows[0]!.id};}
 async run(db:Db,user:CurrentUser,labelId:string,id:string):Promise<VisibilityRun>{
 requireLabelPermission(user,labelId,'research:read');const result=await db.execute(sql`SELECT r.id,r.benchmark_id,r.created_at,b.name,b.course_version_id,b.country,b.language,b.session_type,b.search_mode,b.repeats,b.entity_snapshot FROM visibility_runs r JOIN visibility_benchmarks b ON b.id=r.benchmark_id WHERE r.id=${id} AND b.label_id=${labelId}`);const r=result.rows[0];if(!r)throw AppError.notFoundOrForbidden('visibility_run',id);
 const [ps,es,os,ms,cs]=await Promise.all([db.execute(sql`SELECT p.* FROM visibility_prompts p JOIN visibility_benchmark_prompts bp ON bp.prompt_id=p.id WHERE bp.benchmark_id=${r.benchmark_id}`),db.execute(sql`SELECT engine FROM visibility_benchmark_engines WHERE benchmark_id=${r.benchmark_id}`),db.execute(sql`SELECT * FROM visibility_observations WHERE run_id=${id} ORDER BY captured_at`),db.execute(sql`SELECT m.* FROM visibility_mentions m JOIN visibility_observations o ON o.id=m.observation_id WHERE o.run_id=${id}`),db.execute(sql`SELECT c.* FROM visibility_citations c JOIN visibility_observations o ON o.id=c.observation_id WHERE o.run_id=${id}`)]);
 const entities=z.array(visibilityEntityInput.extend({id:z.uuid()})).parse(r.entity_snapshot);const prompts=ps.rows.map(prompt).map(p=>({...p,kind:promptKind(p.text,entities)}));const engines=es.rows.map(e=>z.enum(['chatgpt','gemini','perplexity','copilot','claude','api_model']).parse(e.engine));
 const observations:VisibilityObservation[]=os.rows.map(o=>({id:str(o.id),promptId:str(o.prompt_id),engine:engines.find(e=>e===o.engine)!,repetition:Number(o.repetition),status:z.enum(['success','blocked','unavailable','extraction_error']).parse(o.status),rawResponse:str(o.raw_response),responseHash:str(o.response_hash),capturedAt:new Date(str(o.captured_at)).toISOString(),model:o.model===null?null:str(o.model),citationCapture:z.enum(['complete','unknown']).parse(o.citation_capture),failureReason:str(o.failure_reason),evidenceUrl:o.evidence_url===null?null:str(o.evidence_url),sanitized:true,captureMethod:'manual_import',citations:cs.rows.filter(c=>c.observation_id===o.id).map(c=>str(c.url)),citedDomains:[...new Set(cs.rows.filter(c=>c.observation_id===o.id).map(c=>str(c.domain)))],mentions:ms.rows.filter(m=>m.observation_id===o.id).flatMap(m=>{const e=entities.find(e=>e.id===m.entity_id);return e?[{entityId:e.id,name:e.name,kind:e.kind,evidence:str(m.evidence)}]:[];})}));
 const total=prompts.length*engines.length*Number(r.repeats);const success=observations.filter(o=>o.status==='success').length;
 return {id,benchmarkId:str(r.benchmark_id),name:str(r.name),courseVersionId:str(r.course_version_id),createdAt:new Date(str(r.created_at)).toISOString(),country:str(r.country),language:str(r.language),sessionType:str(r.session_type),searchMode:str(r.search_mode),repeats:Number(r.repeats),engines,prompts,entities,observations,status:observations.length===0?'pending':observations.length<total?'partial':success===total?'completed':success?'partial':'failed',metrics:metrics(prompts,entities,engines,Number(r.repeats),observations)};
 }
 async import(db:Db,user:CurrentUser,labelId:string,id:string,body:unknown){
 requireLabelPermission(user,labelId,'research:run');const run=await this.run(db,user,labelId,id);const input=await new ManualImportAdapter().capture(body);
 if(!run.prompts.some(p=>p.id===input.promptId)||!run.engines.includes(input.engine)||input.repetition>run.repeats)throw new AppError('validation_failed');
 if(new Date(input.capturedAt).getTime()>Date.now()+300000)throw new AppError('validation_failed',{publicMessage:'Een meting kan niet in de toekomst liggen.'});
 if(input.engine==='api_model'&&!input.model)throw new AppError('validation_failed',{publicMessage:'Vermeld de API-modelnaam; dit is geen consumentenproductmeting.'});
 const hash=createHash('sha256').update(JSON.stringify(input)).digest('hex');
 return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM visibility_runs WHERE id=${id} FOR UPDATE`);const old=(await tx.execute(sql`SELECT id,response_hash FROM visibility_observations WHERE run_id=${id} AND prompt_id=${input.promptId} AND engine=${input.engine} AND repetition=${input.repetition}`)).rows[0];if(old){if(old.response_hash===hash)return {id:old.id};throw new AppError('conflict',{publicMessage:'Deze meetcel is al vastgelegd. Maak een nieuwe run voor een nieuwe waarneming.'});}
 const observationId=randomUUID();await tx.execute(sql`INSERT INTO visibility_observations(id,run_id,prompt_id,engine,repetition,status,raw_response,response_hash,capture_method,captured_at,model,citation_capture,failure_reason,evidence_url,imported_by) VALUES(${observationId},${id},${input.promptId},${input.engine},${input.repetition},${input.status},${input.rawResponse},${hash},'manual_import',${input.capturedAt},${input.model},${input.citationCapture},${input.failureReason},${input.evidenceUrl},${user.userId})`);
 if(input.status==='success'){for(const m of matchedEntities(input.rawResponse,run.entities))await tx.execute(sql`INSERT INTO visibility_mentions VALUES(${observationId},${m.entityId},${m.evidence})`);
 for(const c of input.citations.map(canonicalCitation))await tx.execute(sql`INSERT INTO visibility_citations VALUES(${observationId},${c.url},${c.domain}) ON CONFLICT DO NOTHING`);}
 return {id:observationId};});
 }
 async campaign(db:Db,user:CurrentUser,labelId:string,runId:string,observationId:string){
 requireLabelPermission(user,labelId,'campaign:write');const run=await this.run(db,user,labelId,runId);const o=run.observations.find(o=>o.id===observationId);if(o?.status!=='success')throw new AppError('gate_not_passed');
 const p=run.prompts.find(p=>p.id===o.promptId)!;
 return db.transaction(async tx=>{await tx.execute(sql`SELECT id FROM visibility_observations WHERE id=${observationId} FOR UPDATE`);const prior=(await tx.execute(sql`SELECT campaign_id FROM visibility_actions WHERE observation_id=${observationId}`)).rows[0];if(prior)return {id:str(prior.campaign_id)};
 const absent=!o.mentions.some(m=>m.kind==='own');const suppliedBrief=`AI Visibility — te onderzoeken kans, geen bewezen marktvraag of causaliteit.\nVraag: ${p.text}\nOnderwerp: ${p.topic}\nMotor: ${o.engine}; methode: ${o.captureMethod}; model: ${o.model??'onbekend'}; gemeten: ${o.capturedAt}\nContext: ${run.country}/${run.language}, sessie ${run.sessionType}, zoeken ${run.searchMode}. Context handmatig verklaard.\nWaarneming: ${absent?'eigen merk niet genoemd':'eigen merk genoemd'} in deze ene respons. Eigen bron ${o.citationCapture==='unknown'?'onbekend':o.citedDomains.some(d=>ownDomain(d,run.entities))?'aanwezig':'niet geciteerd'}.\nGenoemde merken: ${o.mentions.map(m=>m.name).join(', ')||'geen gematcht'}\nBronnen: ${o.citations.slice(0,10).map(url=>url.slice(0,300)).join(', ')||'geen vastgelegd'}\nLetterlijke respons:\n${o.rawResponse.slice(0,9000)}\n\nHypothese: verduidelijk de vraag met aantoonbare eigen cursusinformatie; onderzoek of bestaande content verbetering nodig heeft voordat nieuwe content wordt gemaakt. Laat persona en behoefte toetsen. Geen zoekvolume, aanbevelingspositie of juistheidspercentage gemeten.\nKPI: herhaal dezelfde benchmark met dezelfde context; rapporteer waargenomen verschil zonder causaliteitsclaim.\nBewijs: visibility-run ${run.id}; observation ${o.id}; prompt ${p.id} v${String(p.version)}.`;
 // CampaignService needs a Db facade; the transaction has the same query interface.
 const campaign=await this.campaigns.create(tx,user,labelId,createCampaignInput.parse({name:`AI Visibility — ${p.topic}`.slice(0,160),entryMode:'start_from_briefing',courseVersionId:run.courseVersionId,suppliedBrief}));
 await tx.execute(sql`INSERT INTO visibility_actions(observation_id,campaign_id) VALUES(${o.id},${campaign.id})`);return {id:campaign.id};});
 }
}
