import {useState,type ReactNode,type FormEvent} from 'react';
import {useQuery,useMutation} from '@tanstack/react-query';
import {useNavigate} from 'react-router-dom';
import type {LabelSummary,VisibilityEntity,VisibilityPrompt,VisibilityRun} from '@c360/contracts';
import {Button,Card,Notice} from '@c360/ui';
import {api,type ApiClientError} from '../api/client.js';
import {useCourses} from '../api/campaign-queries.js';
import {FlowNavigation} from '../components/FlowNavigation.js';
import './ai-visibility.css';
interface Overview {entities:VisibilityEntity[];prompts:VisibilityPrompt[];benchmarks:{id:string;name:string;course_version_id:string}[];runs:{id:string;name:string;created_at:string}[];}
const engines=['chatgpt','gemini','perplexity','copilot','claude','api_model'];
const engineName=(s:string)=>s==='api_model'?'API-model (geen consumentenproduct)':s;
const kinds:Record<string,string>={unbranded:'Zonder merknaam',branded:'Eigen merk in vraag',competitor_named:'Concurrent in vraag'};
const values=(form:HTMLFormElement)=>new FormData(form);
const string=(d:FormData,key:string)=>(typeof d.get(key)==='string'?d.get(key) as string:'');
const lines=(s:string)=>s.split(/[,\n]/u).map(s=>s.trim()).filter(Boolean);
const percentage=(n:number|null)=>n===null?'Onbekend':`${String(Math.round(n*100))}%`;
export function AiVisibilityPage({label}:{label:LabelSummary|undefined}):ReactNode{return label?<VisibilityLabel key={label.id} label={label}/>:<Notice tone="warning">Kies eerst een label.</Notice>;}
function VisibilityLabel({label}:{label:LabelSummary}):ReactNode{
 const navigate=useNavigate();const base=`/labels/${label.id}/ai-visibility`;
 const [editing,setEditing]=useState('');const [tab,setTab]=useState('setup');const [course,setCourse]=useState('');const [runId,setRunId]=useState('');const [selected,setSelected]=useState<string[]>([]);const [message,setMessage]=useState('');
 const courses=useCourses(label.id);const courseId=course||(courses.data?.items[0]?.course.id??'');
 const overview=useQuery<Overview,ApiClientError>({queryKey:['visibility',label.id],queryFn:({signal})=>api.get(base,signal)});
 const run=useQuery<VisibilityRun,ApiClientError>({queryKey:['visibility-run',label.id,runId],queryFn:({signal})=>api.get(`${base}/runs/${runId}`,signal),enabled:!!runId});
 const write=label.role==='label_manager'||label.role==='label_editor';const approve=label.role==='label_manager'||label.role==='label_approver';
 const mutation=useMutation<{id?:string;created?:number|boolean;similar?:{text:string}[]},ApiClientError,{path:string;body?:unknown;next?:'run'|'campaign';form?:HTMLFormElement}>({mutationFn:input=>api.post(`${base}${input.path}`,input.body),onSuccess:(result,input)=>{void overview.refetch();if(runId)void run.refetch();setMessage(result.created===false?'Deze vraag bestaat al.':result.similar?.length?`Opgeslagen. Vergelijkbare vragen: ${result.similar.map(p=>p.text).join(' · ')}`:'Opgeslagen.');input.form?.reset();if(input.next==='run'&&result.id){setRunId(result.id);setTab('results');}if(input.next==='campaign'&&result.id)void navigate(`/campagnes/${result.id}`);}});
 const send=(path:string,body?:unknown,form?:HTMLFormElement)=>{setMessage('');mutation.mutate({path,body,...(form?{form}:{})});};
 const submit=(event:FormEvent<HTMLFormElement>,fn:(d:FormData,form:HTMLFormElement)=>void)=>{event.preventDefault();fn(values(event.currentTarget),event.currentTarget);};
 const editEntity=overview.data?.entities.find(e=>e.id===editing);
 const prompts=overview.data?.prompts.filter(p=>p.courseVersionId===courseId)??[];
 return <div className="visibility-page"><div className="c360-section-header"><div className="c360-section-header__text"><h2 className="c360-section-title c360-section-title--sm">Handmatige AI-productmetingen</h2><p className="c360-card__hint">Van een controleerbaar AI-antwoord naar een onderbouwde campagnehypothese.</p></div></div>
 <Notice tone="info">Handmatige metingen. Automatisch ophalen uit AI-consumentenproducten is nog niet beschikbaar. API-antwoorden worden apart gemeten. Vermeldingen bewijzen geen aanbeveling, marktvraag of contentkwaliteit.</Notice>
 <FlowNavigation label="AI Visibility" value={tab} onChange={setTab} items={[{id:'setup',label:'1. Merken',panelId:'visibility-setup'},{id:'prompts',label:'2. Vragen & benchmark',panelId:'visibility-prompts'},{id:'results',label:'3. Metingen & bewijs',panelId:'visibility-results'}]}/>
 {overview.isPending&&<p role="status">Laden…</p>}{(overview.error??run.error??mutation.error??courses.error)&&<Notice tone="warning">{(overview.error??run.error??mutation.error??courses.error)?.userMessage}</Notice>}{message&&<p role="status">{message}</p>}
 <section hidden={tab!=='setup'} id="visibility-setup" role="tabpanel" aria-label="Merken"><Card ariaLabel="Meetconfiguratie"><h2>Welke merken volgen we?</h2><p>Voeg één eigen merk en relevante concurrenten toe. Gebruik unieke namen en echte domeinen. Nieuwe benchmarks bewaren een vaste kopie van deze configuratie.</p>
 {overview.data?.entities.map(e=><p key={e.id}><strong>{e.name}</strong> · {e.kind==='own'?'Eigen merk':'Concurrent'} · {e.aliases.join(', ')} · {e.domains.join(', ')}</p>)}
 {write&&<label>Merk bewerken<select value={editing} onChange={e=>setEditing(e.target.value)}><option value="">Nieuw merk</option>{overview.data?.entities.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>}
 {write&&<form key={editing} onSubmit={e=>submit(e,(d,f)=>send(editing?`/entities/${editing}`:'/entities',{name:string(d,'name'),kind:string(d,'kind'),aliases:lines(string(d,'aliases')),domains:lines(string(d,'domains'))},f))}><label>Merknaam<input name="name" defaultValue={editEntity?.name} required minLength={3} maxLength={120}/></label><label>Relatie<select name="kind" defaultValue={editEntity?.kind}><option value="own">Eigen merk</option><option value="competitor">Concurrent</option></select></label><label>Unieke aliassen (komma gescheiden)<input name="aliases" defaultValue={editEntity?.aliases.join(', ')} placeholder="Bijvoorbeeld een andere schrijfwijze"/></label><label>Domeinen (zonder https://)<input name="domains" defaultValue={editEntity?.domains.join(', ')} placeholder="voorbeeld.nl"/></label><Button type="submit" disabled={mutation.isPending}>{editing?'Merk bijwerken':'Merk toevoegen'}</Button></form>}
 </Card></section>
 <section hidden={tab!=='prompts'} id="visibility-prompts" role="tabpanel" aria-label="Vragen en benchmark"><Card ariaLabel="Vragenbibliotheek"><h2>Vragen die je wilt toetsen</h2><label>Opleiding<select value={courseId} onChange={e=>{setCourse(e.target.value);setSelected([]);}}>{courses.data?.items.map(c=><option key={c.course.id} value={c.course.id}>{c.course.name}</option>)}</select></label>
 <p>Voorstellen zijn sjablonen, geen gemeten zoekvragen. Beoordeel relevantie, doelgroep en formulering voordat je ze goedkeurt. Herhalingen tellen niet als extra unieke vragen.</p>
 {write&&<Button disabled={!courseId||mutation.isPending||!overview.data?.entities.some(e=>e.kind==='own')} onClick={()=>send('/proposals',{courseVersionId:courseId})}>24 cursusvragen voorstellen · geen AI-kosten</Button>}
 {write&&<details><summary>Zelf een vraag toevoegen</summary><form onSubmit={e=>submit(e,(d,f)=>send('/prompts',{courseVersionId:courseId,text:string(d,'text'),topic:string(d,'topic'),family:string(d,'family'),intent:string(d,'intent'),persona:string(d,'persona'),source:string(d,'source')},f))}><label>Exacte vraag<textarea name="text" required minLength={10} maxLength={1200}/></label><label>Onderwerp<input name="topic" required minLength={2}/></label><label>Vraagfamilie<input name="family" required minLength={2}/></label><label>Intentie<select name="intent"><option value="discovery">Ontdekken</option><option value="comparison">Vergelijken</option><option value="problem">Probleem oplossen</option><option value="reputation">Reputatie</option></select></label><label>Doelgroep / hypothese<input name="persona"/></label><label>Herkomst (bron of hypothese)<input name="source" required defaultValue="Handmatige hypothese; vraagvolume onbekend"/></label><Button type="submit" disabled={mutation.isPending||!courseId}>Voorstel bewaren</Button></form></details>}
 <div className="visibility-prompts">{prompts.map(p=><article key={p.id}><label><input type="checkbox" disabled={p.state!=='approved'||!write} checked={selected.includes(p.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,p.id]:old.filter(id=>id!==p.id))}/><strong>{p.text}</strong></label><p>{kinds[p.kind]} · {p.family} · {p.state==='approved'?'✓ Goedgekeurd':'Voorstel'}</p><small>{p.source}{p.persona&&` · ${p.persona}`}</small>{approve&&p.state==='proposed'&&<Button disabled={mutation.isPending} onClick={()=>send(`/prompts/${p.id}/approve`)}>Goedkeuren voor meting</Button>}</article>)}</div>
 </Card><Card ariaLabel="Benchmark maken"><h2>Vaste meetset maken</h2><p>{selected.length} goedgekeurde vragen geselecteerd (maximaal 30). Dezelfde meetset kan later opnieuw worden gemeten.</p>{write&&<form onSubmit={e=>submit(e,(d,f)=>send('/benchmarks',{courseVersionId:courseId,name:string(d,'name'),promptIds:selected,engines:d.getAll('engine'),repeats:Number(d.get('repeats')),country:string(d,'country'),language:string(d,'language'),sessionType:string(d,'sessionType'),searchMode:string(d,'searchMode')},f))}><label>Naam<input name="name" required minLength={3}/></label><fieldset><legend>Producten — resultaten blijven gescheiden</legend>{engines.map(engine=><label key={engine}><input type="checkbox" name="engine" value={engine} defaultChecked={engine==='chatgpt'}/>{engineName(engine)}</label>)}</fieldset><label>Herhalingen per vraag<input name="repeats" type="number" min={1} max={5} defaultValue={1}/></label><label>Landcode<input name="country" pattern="[A-Z]{2}" defaultValue="NL" required/></label><label>Taalcode<input name="language" pattern="[a-z]{2}" defaultValue="nl" required/></label><label>Sessie<select name="sessionType"><option value="fresh">Nieuwe / tijdelijke sessie</option><option value="personalized">Gepersonaliseerd</option><option value="unknown">Onbekend</option></select></label><label>Webzoeken<select name="searchMode"><option value="unknown">Onbekend</option><option value="on">Aan</option><option value="off">Uit</option></select></label><Button type="submit" disabled={mutation.isPending||!selected.length||selected.length>30}>Meetset vastleggen</Button></form>}
 {overview.data?.benchmarks.filter(b=>b.course_version_id===courseId).map(b=><p key={b.id}>{b.name} {write&&<Button disabled={mutation.isPending} onClick={()=>mutation.mutate({path:`/benchmarks/${b.id}/runs`,body:{requestKey:crypto.randomUUID()},next:'run'})}>Nieuwe meetronde</Button>}</p>)}
 </Card></section>
 <section hidden={tab!=='results'} id="visibility-results" role="tabpanel" aria-label="Metingen en bewijs"><label>Meetronde<select value={runId} onChange={e=>setRunId(e.target.value)}><option value="">Kies een meetronde</option>{overview.data?.runs.map(r=><option key={r.id} value={r.id}>{r.name} · {new Date(r.created_at).toLocaleString('nl-NL')}</option>)}</select></label>{!overview.data?.runs.length&&<p>Nog geen metingen. Configureer merken, keur vragen goed en maak een meetset.</p>}
 {run.data&&<RunPanel key={run.data.id} run={run.data} write={write} pending={mutation.isPending} onImport={(body,form)=>send(`/runs/${runId}/observations`,body,form)} onCampaign={id=>mutation.mutate({path:`/runs/${runId}/campaigns`,body:{observationId:id},next:'campaign'})}/>}
 </section></div>;
}
function RunPanel({run,write,pending,onImport,onCampaign}:{run:VisibilityRun;write:boolean;pending:boolean;onImport:(body:unknown,form:HTMLFormElement)=>void;onCampaign:(id:string)=>void}):ReactNode{
 const [engine,setEngine]=useState<string>(run.engines[0]!);const [kind,setKind]=useState('unbranded');const [status,setStatus]=useState('success');
 const metric=run.metrics.find(m=>m.engine===engine&&m.kind===kind);
 const cells=run.prompts.flatMap(p=>run.engines.flatMap(e=>Array.from({length:run.repeats},(_,i)=>({key:`${p.id}|${e}|${String(i+1)}`,prompt:p,engine:e,repetition:i+1,observation:run.observations.find(o=>o.promptId===p.id&&o.engine===e&&o.repetition===i+1)}))));
 const missing=cells.filter(c=>!c.observation);
 return <><Card ariaLabel="Meetresultaten"><h2>{run.name}</h2><p>{run.country}/{run.language} · sessie: {run.sessionType} · webzoeken: {run.searchMode} · {run.observations.length}/{cells.length} cellen vastgelegd. Context is handmatig verklaard.</p><label>Product<select value={engine} onChange={e=>setEngine(e.target.value)}>{run.engines.map(e=><option key={e} value={e}>{engineName(e)}</option>)}</select></label><label>Vraagcategorie<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 {metric&&<><dl className="visibility-metrics"><div><dt>Eigen merk genoemd</dt><dd>{percentage(metric.mentionRate)}</dd><small>{metric.mentionCount}/{metric.successful} geslaagde antwoorden</small></div><div><dt>Eigen domein geciteerd</dt><dd>{percentage(metric.citationRate)}</dd><small>{metric.ownCitationCount}/{metric.citationEligible} antwoorden met volledig vastgelegde bronnen</small></div><div><dt>Dekking</dt><dd>{metric.completed}/{metric.planned}</dd><small>{metric.failed} mislukt · {metric.uniquePrompts} unieke vragen met antwoord</small></div></dl><p>Aandeel vermeldingen binnen de ingestelde merken: {metric.entities.map(e=>`${e.name}: ${percentage(e.shareOfVoice)} (${String(e.mentions)})`).join(' · ')}. Per antwoord telt een merk maximaal één keer.</p></>}
 <Notice tone="info">Aanbevelingssterkte, positie en feitelijke juistheid: niet beoordeeld. Dit is een steekproef van antwoorden, geen bereik- of marktaandeelmeting. Een verschil tussen meetrondes bewijst geen effect van content.</Notice>
 <Button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(run,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`ai-visibility-${run.id}.json`;a.click();URL.revokeObjectURL(url);}}>Bewijs & meetdefinitie downloaden</Button></Card>
 {write&&missing.length>0&&<Card ariaLabel="Antwoord registreren"><h2>Echt antwoord vastleggen</h2><p>Stel de exacte vraag in het gekozen product, in de afgesproken sessie. Kopieer het volledige antwoord en leg de getoonde bronlinks vast. Leg blokkades vast als mislukt. Verwijder persoonsgegevens vóór opslag; plak geen inloggegevens.</p><form onSubmit={e=>{e.preventDefault();const d=values(e.currentTarget);const [promptId,selectedEngine,repetition]=string(d,'cell').split('|');onImport({promptId,engine:selectedEngine,repetition:Number(repetition),status,rawResponse:status==='success'?string(d,'rawResponse'):'',capturedAt:new Date(string(d,'capturedAt')).toISOString(),model:string(d,'model')||null,citations:status==='success'?lines(string(d,'citations')):[],citationCapture:status==='success'?string(d,'citationCapture'):'unknown',failureReason:status==='success'?'':string(d,'failureReason'),evidenceUrl:string(d,'evidenceUrl')||null,sanitized:true},e.currentTarget);}}><label>Open meetcel<select name="cell">{missing.map(c=><option key={c.key} value={c.key}>{engineName(c.engine)} · #{c.repetition} · {c.prompt.text}</option>)}</select></label><label>Uitkomst<select value={status} onChange={e=>setStatus(e.target.value)}><option value="success">Antwoord ontvangen</option><option value="blocked">Geblokkeerd</option><option value="unavailable">Niet beschikbaar</option><option value="extraction_error">Antwoord niet betrouwbaar vastgelegd</option></select></label><label>Tijdstip van de waarneming (lokale tijd)<input name="capturedAt" type="datetime-local" required/></label><label>Getoonde modelnaam (verplicht voor API-model)<input name="model" maxLength={120}/></label>{status==='success'?<><label>Volledig antwoord<textarea name="rawResponse" required minLength={20} maxLength={50000} rows={8}/></label><label>Bronlinks uit het antwoord (één per regel)<textarea name="citations" rows={3}/></label><label>Bronregistratie<select name="citationCapture"><option value="unknown">Niet volledig / onbekend</option><option value="complete">Alle getoonde bronnen vastgelegd (ook als er geen waren)</option></select></label></>:<label>Reden<textarea name="failureReason" required minLength={5}/></label>}<label>Openbare bewijslink (optioneel, HTTPS)<input name="evidenceUrl" type="url"/></label><label><input type="checkbox" required/> Ik heb persoonsgegevens verwijderd en de product-, vraag- en sessiecontext gecontroleerd. De bronregistratie is correct.</label><Button type="submit" disabled={pending}>Ongewijzigde waarneming bewaren</Button></form></Card>}
 <Card ariaLabel="Bewijs per antwoord"><h2>Van antwoord naar onderzoekskans</h2><p>Een merkvermelding wordt via namen, aliassen of domeinen herkend. Controleer het antwoord zelf. Een campagne begint als hypothese en volgt de bestaande cursus-, merk- en briefingcontroles.</p>{run.observations.map(o=><details key={o.id}><summary>{engineName(o.engine)} · #{o.repetition} · {run.prompts.find(p=>p.id===o.promptId)?.text} · {o.status}</summary><p>{new Date(o.capturedAt).toLocaleString('nl-NL')} · model: {o.model??'onbekend'} · handmatig geïmporteerd</p>{o.status==='success'?<><p>Gevonden: {o.mentions.map(m=>m.name).join(', ')||'geen ingestelde merken'}. Bronnen: {o.citationCapture==='complete'?'volledig vastgelegd':'onbekend / onvolledig'}.</p><pre>{o.rawResponse}</pre>{o.mentions.map(m=><p key={m.entityId}>{m.evidence}</p>)}<ul>{o.citations.map(url=><li key={url}><a href={url} target="_blank" rel="noreferrer">{url}</a></li>)}</ul>{write&&<Button disabled={pending} onClick={()=>onCampaign(o.id)}>Onderzoek als campagne</Button>}</>:<p>{o.failureReason}</p>}{o.evidenceUrl&&<a href={o.evidenceUrl} target="_blank" rel="noreferrer">Open bewijslink</a>}<small>Waarneming: {o.id} · hash: {o.responseHash}</small></details>)}</Card></>;
}
