import {useState,type ReactNode} from 'react';
import {useQuery,useMutation} from '@tanstack/react-query';
import {useSearchParams} from 'react-router-dom';
import type {LabelSummary,GeoSetup,GeoReport,GeoEngineAnswer,JobSummary} from '@c360/contracts';
import {Button,Card,Notice} from '@c360/ui';
import {api,type ApiClientError} from '../api/client.js';
import {useCourses} from '../api/campaign-queries.js';
import {FlowNavigation} from '../components/FlowNavigation.js';
import {AiVisibilityPage} from './AiVisibilityPage.js';
import './ai-visibility.css';
const finished=new Set(['succeeded','dead','failed','cancelled']);
function download(name:string,text:string,type='text/markdown'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function GeoPage({label}:{label:LabelSummary|undefined}):ReactNode{return label?<GeoLabel key={label.id} label={label}/>:<Notice tone="warning">Kies een label.</Notice>;}
function GeoLabel({label}:{label:LabelSummary}):ReactNode{
 const [course,setCourse]=useState('');const [tab,setTab]=useState('new');const [search,setSearch]=useState('');const [params,setParams]=useSearchParams();
 const courses=useCourses(label.id);const courseId=course||((params.get('label')===label.id?params.get('course'):null)??courses.data?.items[0]?.course.id??'');const base=`/labels/${label.id}/ai-visibility/geo`;
 const history=useQuery<{items:{id:string;course_version_id:string;course_name:string;created_at:string;summary:string;is_mock:string}[]},ApiClientError>({queryKey:['geo-history',label.id,search],queryFn:({signal})=>api.get(`${base}/reports?search=${encodeURIComponent(search)}`,signal),enabled:tab==='history'});
 return <div className="visibility-page"><header><h1>AI Visibility & GEO</h1><p>Onderzoek vragen van je doelgroep. Ontvang concrete voorstellen voor de cursuspagina en je blog.</p><strong>Actief label: {label.name}</strong></header>
 <FlowNavigation label="GEO werkruimte" value={tab} onChange={setTab} items={[{id:'new',label:'Onderzoek & advies',panelId:'geo-new'},{id:'history',label:'Bewaarde onderzoeken',panelId:'geo-history'}]}/>
 {(courses.error??history.error)&&<Notice tone="warning">{(courses.error??history.error)?.userMessage}</Notice>}
 <section id="geo-new" role="tabpanel" aria-label="Onderzoek en advies" hidden={tab!=='new'}><Card ariaLabel="Actieve opleiding"><label>Opleiding<select aria-label="Opleiding" value={courseId} onChange={e=>{setCourse(e.target.value);setParams({});}}>{courses.data?.items.map(c=><option value={c.course.id} key={c.course.id}>{c.course.name}</option>)}</select></label>{!courseId&&<p>Voeg eerst een opleiding toe in Opleidingen.</p>}</Card>
 {courseId&&<GeoCourse key={courseId} label={label} courseId={courseId} selectedReport={params.get('label')===label.id?(params.get('report')??''):''} onReport={id=>setParams(id?{report:id,label:label.id,course:courseId}:{})} onSaved={()=>{void history.refetch();}}/>}
 </section>
 <section id="geo-history" role="tabpanel" aria-label="Bewaarde onderzoeken" hidden={tab!=='history'}><Card ariaLabel="Onderzoek terugvinden"><h2>Bewaard voor {label.name}</h2><label>Zoeken op opleiding, vraag of inhoud<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Bijvoorbeeld CROV of vaardigheden"/></label>{history.isPending&&<p>Laden…</p>}{history.data?.items.length===0&&<p>Nog geen passende onderzoeken gevonden.</p>}{history.data?.items.map(r=><article key={r.id}><h3>{r.course_name}</h3><p>{new Date(r.created_at).toLocaleString('nl-NL')}{r.is_mock==='true'?' · Testdata':''}</p><p>{r.summary}</p><Button onClick={()=>{setCourse(r.course_version_id);setParams({report:r.id,label:label.id,course:r.course_version_id});setTab('new');}}>Onderzoek openen</Button></article>)}</Card></section>
 <details><summary>Geavanceerd: handmatige AI-productmetingen</summary><p>Losse metingen in consumentenproducten blijven apart van webonderzoek.</p><AiVisibilityPage label={label}/></details>
 </div>;
}
function GeoCourse({label,courseId,selectedReport,onReport,onSaved}:{label:LabelSummary;courseId:string;selectedReport:string;onReport:(id:string)=>void;onSaved:()=>void}):ReactNode{
 const base=`/labels/${label.id}/ai-visibility/geo`;
 const setup=useQuery<GeoSetup,ApiClientError>({queryKey:['geo-setup',label.id,courseId],queryFn:({signal})=>api.get(`${base}/setup/${courseId}`,signal)});
 const latest=useQuery<{job:JobSummary|null;reportId?:string|null},ApiClientError>({queryKey:['geo-job',label.id,courseId],queryFn:({signal})=>api.get(`${base}/latest/${courseId}`,signal),refetchInterval:q=>q.state.data?.job&&!finished.has(q.state.data.job.status)?2000:false});
 const captured=useQuery<GeoEngineAnswer[],ApiClientError>({queryKey:['geo-answers',label.id,latest.data?.job?.id,latest.data?.job?.status],queryFn:({signal})=>api.get(`${base}/answers/${latest.data!.job!.id}`,signal),enabled:!!latest.data?.job,refetchInterval:q=>latest.data?.job&&!finished.has(latest.data.job.status)&&!q.state.data?.length?3000:false});
 const job=latest.data?.job;const automaticId=job?.status==='succeeded'&&typeof job.result?.reportId==='string'?job.result.reportId:'';
 const reportId=selectedReport||automaticId||(latest.data?.reportId??'');
 const report=useQuery<GeoReport,ApiClientError>({queryKey:['geo-report',label.id,reportId,job?.status],queryFn:({signal})=>api.get(`${base}/reports/${reportId}`,signal),enabled:!!reportId});
 const busy=!!job&&!finished.has(job.status);const canWrite=label.role==='label_manager'||label.role==='label_editor';
 return <>{(setup.error??latest.error??report.error)&&<Notice tone="warning">{(setup.error??latest.error??report.error)?.userMessage}</Notice>}
 {setup.data&&(report.data?<details><summary>Nieuw onderzoek starten of vragen aanpassen</summary><ResearchForm setup={setup.data} canWrite={canWrite} busy={busy} base={base} courseId={courseId} onStart={async()=>{onReport('');await latest.refetch();await setup.refetch();onSaved();}}/></details>:<ResearchForm key={`${courseId}:${setup.data.courseUrl??''}`} setup={setup.data} canWrite={canWrite} busy={busy} base={base} courseId={courseId} onStart={async()=>{onReport('');await latest.refetch();await setup.refetch();onSaved();}}/>)}
 {job&&<Card ariaLabel="Voortgang"><h2>{busy?'Onderzoek loopt':'Laatste onderzoek'}</h2><p>{job.progress?.message??job.status}</p>{busy&&<p>Je kunt deze pagina sluiten; het onderzoek loopt op de achtergrond door.</p>}{job.failureMessage&&<Notice tone="warning">{captured.data?.some(a=>a.status==='succeeded')?'ChatGPT-antwoorden zijn bewaard. De vervolgstap is niet voltooid. Opnieuw proberen gebruikt dezelfde antwoorden.':job.failureMessage}</Notice>}{job.retryable&&canWrite&&<Retry jobId={job.id} onRetry={()=>{void latest.refetch();}}/>}</Card>}
 {captured.data&&captured.data.length>0&&(!report.data||report.data.jobId!==job?.id)&&<Card ariaLabel="Opgehaalde ChatGPT-antwoorden"><EngineAnswers answers={captured.data} labelName={label.name}/></Card>}
 {report.data&&<ReportView key={report.data.id} report={report.data}/>}
 </>;
}
function Retry({jobId,onRetry}:{jobId:string;onRetry:()=>void}):ReactNode{const retry=useMutation<unknown,ApiClientError>({mutationFn:()=>api.post(`/jobs/${jobId}/retry`),onSuccess:onRetry});return <>{retry.error&&<Notice tone="warning">{retry.error.userMessage}</Notice>}<Button disabled={retry.isPending} onClick={()=>retry.mutate()}>Opnieuw proberen</Button></>;}
function ResearchForm({setup,canWrite,busy,base,courseId,onStart}:{setup:GeoSetup;canWrite:boolean;busy:boolean;base:string;courseId:string;onStart:()=>Promise<void>}):ReactNode{
 const [mode,setMode]=useState<'web_research'|'chatgpt'>(setup.canMeasureChatgpt?'chatgpt':'web_research');
 const [questions,setQuestions]=useState(setup.questions);const [selected,setSelected]=useState(setup.questions.map(()=>true));const [url,setUrl]=useState(setup.courseUrl??'');const [key,setKey]=useState(()=>crypto.randomUUID());
 const start=useMutation<JobSummary,ApiClientError>({mutationFn:()=>api.post(`${base}/start`,{mode,courseVersionId:courseId,courseUrl:url,questions:questions.filter((_,i)=>selected[i]),approved:true,requestKey:key}),onSuccess:async()=>{setKey(crypto.randomUUID());await onStart();}});
 return <Card ariaLabel="Vragen controleren"><h2>1. Controleer de vragen en start</h2><p>Label en cursus zijn ingevuld. Selecteer of wijzig de vragen; we zoeken bronnen en onderzoeken wat jouw pagina hierover uitlegt.</p><form onSubmit={e=>{e.preventDefault();start.mutate();}}><label>Onderzoeksmethode<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="chatgpt" disabled={!setup.canMeasureChatgpt}>ChatGPT-antwoorden → bronnen vergelijken → siteadvies</option><option value="web_research">Alleen webonderzoek</option></select></label>{!setup.canMeasureChatgpt&&<p>ChatGPT-metingen worden beschikbaar zodra Bright Data op de server is ingesteld.</p>}<label>Cursuspagina<input aria-label="Cursuspagina" type="url" value={url} onChange={e=>setUrl(e.target.value)} required placeholder="https://…"/></label><small>Deze URL wordt bij de opleiding onthouden. Je hoeft hem maar één keer in te vullen als hij nog ontbreekt.</small>
 {questions.map((q,i)=><div className="geo-question" key={i}><label><input aria-label={`Vraag ${String(i+1)} meenemen`} type="checkbox" checked={selected[i]} onChange={e=>setSelected(old=>old.map((v,j)=>j===i?e.target.checked:v))}/>Vraag {i+1}</label><textarea aria-label={`Vraag ${String(i+1)}`} value={q} onChange={e=>setQuestions(old=>old.map((v,j)=>j===i?e.target.value:v))} minLength={10} maxLength={500} required={selected[i]}/></div>)}
 <p>{mode==='chatgpt'?'Elke gekozen vraag wordt ongewijzigd aan ChatGPT gesteld via Bright Data, vanuit Nederland met webzoeken toegestaan. Daarna lezen we bronnen en maken we siteadvies. Maximaal vijf metingen; providerkosten staan los van de AI-analyse en hangen af van je Bright Data-tegoed.':'Automatisch webonderzoek: één zoekstap en één analysestap.'} Vragen zijn voorstellen, geen gemeten zoekvolume. Controleer dat je vraag geen gewenst merkantwoord voorschrijft.</p>{mode==='web_research'&&!setup.canSearch&&<Notice tone="warning">Webzoeken is niet beschikbaar bij de ingestelde provider.</Notice>}{start.error&&<Notice tone="warning">{start.error.userMessage}</Notice>}
 <Button type="submit" disabled={!canWrite||busy||start.isPending||(mode==='chatgpt'?!setup.canMeasureChatgpt:!setup.canSearch)||!selected.some(Boolean)}>{start.isPending?'Onderzoek starten…':'Vragen goedkeuren & onderzoek starten'}</Button></form></Card>;
}
function ReportView({report:r}:{report:GeoReport}):ReactNode{
 const [tab,setTab]=useState(r.engineAnswers?'answers':'advice');
 const markdown=`# GEO-onderzoek: ${r.courseName}\n\nConcept voor inhoudelijke controle. ${r.createdAt}\nCursuspagina: ${r.courseUrl}\n\n${r.analysis.summary}\n\n${r.analysis.items.map(i=>`## ${i.question}\n\n${i.finding}\n\n${i.pageChange?`### Cursuspagina — ${i.pageChange.placement}\n${i.pageChange.reason}\n\n${i.pageChange.proposedText}`:''}\n\n${i.blog?`### Blog: ${i.blog.title}\n\n${i.blog.body}\n\n[${i.blog.internalLinkText}](${r.courseUrl})`:''}\n\nBeperkingen: ${i.limitations}\n\n${i.evidence.map(e=>`Bron: ${e.url}\n> ${e.quote}`).join('\n\n')}`).join('\n\n')}\n\nOnderzoek-ID: ${r.id}`;
 return <Card ariaLabel="Bewaard GEO-advies"><h2>Onderzoek voor {r.courseName}</h2><p>✓ Automatisch bewaard · {new Date(r.createdAt).toLocaleString('nl-NL')} · {r.labelName}</p>{r.isMock&&<Notice tone="warning">Testresultaat — geen echte marktmeting.</Notice>}{!r.engineAnswers&&<p>{r.analysis.summary}</p>}<p><a href={r.courseUrl} target="_blank" rel="noreferrer">Onderzochte cursuspagina</a></p><Notice tone="info">Dit zijn tekstvoorstellen voor controle, geen goedgekeurde publicaties of bewezen zichtbaarheidstoename. Controleer feiten, merktoon en bestaande pagina-inhoud voor plaatsing.</Notice>
 {r.analysisStatus==='unavailable'&&<Notice tone="warning">{r.analysis.summary}</Notice>}
 <Button disabled={r.analysisStatus==='unavailable'} onClick={()=>download(`geo-${r.id}.md`,markdown)}>Pagina- en blogvoorstellen downloaden</Button> <Button onClick={()=>download(`geo-bewijs-${r.id}.json`,JSON.stringify(r,null,2),'application/json')}>Bronnen & onderzoek downloaden</Button>
 <FlowNavigation label="Onderzoeksresultaat" value={tab} onChange={setTab} items={[...(r.engineAnswers?[{id:'answers',label:'1. ChatGPT-antwoorden',panelId:'geo-answers'},{id:'comparison',label:'2. Vergelijking',panelId:'geo-comparison'}]:[]),{id:'advice',label:r.engineAnswers?'3. Pagina & blog':'Pagina & blog',panelId:'geo-advice'},{id:'sources',label:'Bronnen & beperkingen',panelId:'geo-sources'}]}/>
 {r.engineAnswers&&<><section id="geo-answers" role="tabpanel" aria-label="ChatGPT-antwoorden" hidden={tab!=='answers'}><EngineAnswers answers={r.engineAnswers} labelName={r.labelName}/></section><section id="geo-comparison" role="tabpanel" aria-label="Vergelijking" hidden={tab!=='comparison'}><p>{r.analysis.summary}</p><p>Analyse van de opgeslagen antwoorden en gelezen pagina’s. Bronpassages onderbouwen de vergelijking; het zijn geen bewezen oorzaken van een vermelding.</p>{r.analysis.items.map((i,n)=><article key={n}><h3>{i.question}</h3><p>{i.finding}</p>{i.evidence.map((e,j)=><blockquote key={j}>{e.quote}<br/><a href={e.url} target="_blank" rel="noreferrer">{e.url}</a></blockquote>)}<p>{i.limitations}</p></article>)}</section></>}
 <section id="geo-advice" role="tabpanel" aria-label="Pagina en blog" hidden={tab!=='advice'}>{r.analysisStatus==='unavailable'&&<p>De analyse is nog niet voltooid. Er zijn nog geen onderbouwde tekstvoorstellen.</p>}{r.analysis.items.map((i,n)=><article key={n}><h3>{i.question}</h3><p>{i.relevance==='relevant'?'Relevant voor deze cursus':i.relevance==='not_relevant'?'Geen passende cursuskoppeling':'Relevantie onvoldoende onderbouwd'}</p><p>{i.finding}</p>{i.pageChange&&<><h4>Wijziging cursuspagina: {i.pageChange.placement}</h4><p>{i.pageChange.reason}</p><pre>{i.pageChange.proposedText}</pre></>}{i.blog&&<><h4>Blogvoorstel: {i.blog.title}</h4><pre>{i.blog.body}</pre><p>Interne link: <a href={r.courseUrl} target="_blank" rel="noreferrer">{i.blog.internalLinkText}</a></p><Button onClick={()=>download(`blog-${String(n+1)}.md`,`# ${i.blog!.title}\n\n${i.blog!.body}\n\n[${i.blog!.internalLinkText}](${r.courseUrl})\n\nConcept — controleer voor publicatie.`)}>Deze blog downloaden</Button></>}{!i.pageChange&&!i.blog&&<p>Geen tekstvoorstel: onvoldoende relevant bewijs.</p>}<p>{i.limitations}</p><details><summary>Waar komt dit advies vandaan?</summary>{i.evidence.map((e,j)=><blockquote key={j}>{e.quote}<br/><a href={e.url} target="_blank" rel="noreferrer">{e.url}</a></blockquote>)}</details></article>)}</section>
 <section id="geo-sources" role="tabpanel" aria-label="Bronnen en beperkingen" hidden={tab!=='sources'}><p>Gelezen tekst is maximaal 12.000 tekens per pagina. Citaten zijn tegen deze opgeslagen tekst gecontroleerd. Dit is geen volledige technische site-audit.</p>{r.pages.map((p,n)=><details key={n}><summary>{p.role==='course_page'?'Cursuspagina':'Externe bron'} · {p.url}</summary><p>{p.retrievedAt}</p><pre>{p.text}</pre></details>)}{r.failures.map((f,n)=><p key={n}>{f.url}: {f.reason}</p>)}<small>Onderzoek: {r.id} · Merkreferentie: {r.brandVersionId} · Prompt: {r.promptVersion}</small></section>
 </Card>;
}

function EngineAnswers({answers,labelName}:{answers:GeoEngineAnswer[];labelName:string}):ReactNode{
 return <><h3>Wat antwoordde ChatGPT?</h3><p>Letterlijke antwoordtekst via Bright Data. Dit is een momentopname per vraag; geen algemene ranking. De vermelding hieronder is een exacte tekstcontrole op de labelnaam, geen herkenning van alle merknamen.</p>{answers.map((a,i)=><article key={i}><h4>{a.question}</h4>{a.status==='failed'?<Notice tone="warning">{a.error}</Notice>:<><p>{a.answer.toLocaleLowerCase().includes(labelName.toLocaleLowerCase())?`✓ ${labelName} genoemd`:`Labelnaam ${labelName} niet letterlijk gevonden`}</p><p>Land: {a.country??'onbekend'} · Model: {a.model??'niet aangeleverd'} · Webzoeken: {a.webSearchTriggered===null?'onbekend':a.webSearchTriggered?'uitgevoerd':'niet uitgevoerd'} · {a.capturedAt??'Tijdstip niet aangeleverd'}</p><pre>{a.answer}</pre><p>{a.citationStatus==='unknown'?'Citaatkoppelingen niet aangeleverd; onderstaande zoekbronnen en links bewijzen geen koppeling met een specifieke zin.':'Citaatlinks aangeleverd door de collector.'}</p>{a.sources.map((s,n)=><p key={n}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a> · {s.kind==='citation'?'Citaatlink':s.kind==='search_source'?'Zoekbron':'Bijgevoegde link'}</p>)}</>}</article>)}</>;
}
